#!/usr/bin/env bash
# Run one ai-config hook command from the hooks-only skills-directory plugin,
# unless the ai-config marketplace plugin is enabled, in which case that plugin
# already runs the same hook and this copy exits 0 so nothing fires twice.
# See skills/ai-config-hooks/README.md.
#
# Usage (as generated by scripts/gen-hooks-plugin.py):
#   run-hook.sh '<shell command referencing ${CLAUDE_PLUGIN_ROOT}>'
#
# "Enabled" follows Claude Code's scope precedence for enabledPlugins
# (memories/claude-code-settings.md): the highest-precedence settings file
# that names an ai-config@<marketplace> entry decides, and a `false` there
# really does switch off what a lower scope enabled. Local > project > user.
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "run-hook.sh: expected exactly one argument (the hook command)" >&2
  exit 2
fi

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
export CLAUDE_PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$here}"

project="${CLAUDE_PROJECT_DIR:-$here/../..}"
for settings in \
  "$project/.claude/settings.local.json" \
  "$project/.claude/settings.json" \
  "${HOME:-}/.claude/settings.json"; do
  [ -f "$settings" ] || continue
  # First ai-config@* entry in this file, value included; `|| true` because
  # a file that names no such entry is the common case, not an error.
  entry="$(grep -Eo '"ai-config@[^"]+" *: *(true|false)' "$settings" | head -1 || true)"
  [ -n "$entry" ] || continue
  case "$entry" in
    *true) exit 0 ;;
    *) break ;;
  esac
done

exec bash -c "$1"
