#!/usr/bin/env bash
# Run one ai-config hook command from the hooks-only skills-directory plugin,
# unless the ai-config marketplace plugin is enabled in user settings, in which
# case that plugin already runs the same hook and this copy exits 0 so nothing
# fires twice. See skills/ai-config-hooks/README.md.
#
# Usage (as generated by scripts/gen-hooks-plugin.py):
#   run-hook.sh '<shell command referencing ${CLAUDE_PLUGIN_ROOT}>'
set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "run-hook.sh: expected exactly one argument (the hook command)" >&2
  exit 2
fi

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
export CLAUDE_PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$here}"

user_settings="${HOME:-}/.claude/settings.json"
if [ -f "$user_settings" ] \
  && grep -Eq '"ai-config@[^"]+" *: *true' "$user_settings"; then
  exit 0
fi

exec bash -c "$1"
