#!/usr/bin/env python3
"""Generate the hooks manifest of the hooks-only skills-directory plugin.

`hooks/hooks.json` is the canonical hook catalog. Claude Code loads it only
through the ai-config marketplace plugin, which a session that opens this
checkout itself (a remote/web session in ai-config) never installs, so every
hook is inert there (ai-config#2004).

`skills/ai-config-hooks/` is a plugin Claude Code discovers in place from the
project's `.claude/skills/` (a symlink to `skills/`), with no marketplace and
no install step. Its `hooks/hooks.json` is this script's output: the canonical
catalog with each command routed through `run-hook.sh` and its script path
pointed two levels up, at the checkout's own `hooks/`.

    python3 scripts/gen-hooks-plugin.py          # rewrite the generated file
    python3 scripts/gen-hooks-plugin.py --check  # exit 1 if it is out of date
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "hooks" / "hooks.json"
TARGET = ROOT / "skills" / "ai-config-hooks" / "hooks" / "hooks.json"

PLUGIN_HOOKS = "${CLAUDE_PLUGIN_ROOT}/hooks/"
CHECKOUT_HOOKS = "${CLAUDE_PLUGIN_ROOT}/../../hooks/"
RUNNER = "${CLAUDE_PLUGIN_ROOT}/run-hook.sh"

COMMENT = [
    "GENERATED by scripts/gen-hooks-plugin.py from hooks/hooks.json --",
    "do not edit; edit hooks/hooks.json and rerun the script.",
    "Each command runs through run-hook.sh, which yields when the ai-config",
    "marketplace plugin is enabled, and points at the checkout's hooks/ so the",
    "hooks that fire are the ones in the working tree, not a cached copy.",
]


def rewrite_command(command: str) -> str:
    """Route one canonical hook command through the plugin's runner."""
    if PLUGIN_HOOKS not in command:
        raise ValueError(f"command does not reference {PLUGIN_HOOKS}: {command}")
    if "'" in command:
        raise ValueError(f"command contains a single quote: {command}")
    return f"{RUNNER} '{command.replace(PLUGIN_HOOKS, CHECKOUT_HOOKS)}'"


def generate(catalog: dict) -> dict:
    """Return the plugin manifest for a canonical `hooks/hooks.json` dict."""
    events = {}
    for event, groups in catalog["hooks"].items():
        new_groups = []
        for group in groups:
            new_group = dict(group)
            new_group["hooks"] = [
                {**hook, "command": rewrite_command(hook["command"])}
                for hook in group["hooks"]
            ]
            new_groups.append(new_group)
        events[event] = new_groups
    return {"_comment": COMMENT, "hooks": events}


def render(manifest: dict) -> str:
    return json.dumps(manifest, indent=2) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    expected = render(generate(json.loads(SOURCE.read_text(encoding="utf-8"))))
    rel = TARGET.relative_to(ROOT)
    if check:
        actual = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        if actual != expected:
            print(f"{rel} is out of date with hooks/hooks.json; "
                  "run python3 scripts/gen-hooks-plugin.py")
            return 1
        print(f"{rel} matches hooks/hooks.json")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
